extends SceneTree
## Headless checks for the ship data rules and stats. Run from the project folder:
##   godot --headless --script res://tests/test_ship.gd

var failures := 0


func check(cond: bool, label: String) -> void:
	if cond:
		print("  ok    ", label)
	else:
		print("  FAIL  ", label)
		failures += 1


func has_warning(st: Dictionary, prefix: String) -> bool:
	return st.warnings.any(func(w: String) -> bool: return w.begins_with(prefix))


func _init() -> void:
	var lib := ModuleLibrary.new()

	print("rotation")
	check(ShipGrid.rotate_cell(Vector3i(1, 0, 0), 1) == Vector3i(0, 0, -1), "+X turns to -Z")
	check(ShipGrid.rotate_cell(Vector3i(1, 0, 2), 4) == Vector3i(1, 0, 2), "four turns is identity")
	check(ShipGrid.rotate_cell(Vector3i(0, 1, 0), 3) == Vector3i(0, 1, 0), "up is unchanged")

	print("door placement rules")
	var ship := ShipData.new(lib)
	check(ship.add(&"cockpit", Vector3i(0, 0, 0), 0) == "", "first module goes anywhere")
	check(ship.add(&"corridor", Vector3i(0, 0, 0), 0) != "", "overlap rejected")
	check(ship.add(&"corridor", Vector3i(5, 0, 5), 0) != "", "floating module rejected")
	check(ship.add(&"corridor", Vector3i(0, 0, 1), 1) != "", "wrongly rotated corridor rejected")
	check(ship.add(&"corridor", Vector3i(0, 0, 1), 0) == "", "corridor snaps behind cockpit")
	check(ship.add(&"engineering", Vector3i(0, 0, 2), 0) == "", "engineering snaps onto corridor end")

	print("external mounts")
	check(ship.add(&"engine", Vector3i(0, 0, 3), 0) == "", "engine bolts onto bare rear hull face")
	var doorway_test := ShipData.new(lib)
	doorway_test.add(&"cockpit", Vector3i(0, 0, 0), 0)
	check(doorway_test.add(&"engine", Vector3i(0, 0, 1), 0) != "", "engine can't bolt over a doorway")
	check(ship.add(&"frame", Vector3i(1, 0, 1), 0) == "", "frame bolts onto a corridor's side")
	check(ship.add(&"tank", Vector3i(2, 0, 1), 0) == "", "tank bolts onto the frame")
	check(ship.add(&"radiator", Vector3i(1, 0, 0), 0) == "", "radiator bolts onto cockpit side")
	check(ship.add(&"frame", Vector3i(6, 0, 6), 0) != "", "floating frame rejected")
	check(ship.add(&"corner", Vector3i(0, 1, 1), 0) != "", "pressurised module can't float on a door-less hull face")
	check(ship.modules.size() == 7, "seven modules placed")

	print("removal")
	check(ship.remove_at(Vector3i(0, 0, 1)) != "", "removing the middle is refused")
	check(ship.modules.size() == 7, "ship unchanged after refusal")
	check(ship.remove_at(Vector3i(2, 0, 1)) == "", "removing the tank works")
	check(ship.modules.size() == 6, "six modules left")

	print("multi-cell and vertical")
	var s2 := ShipData.new(lib)
	check(s2.add(&"room_2x2", Vector3i(0, 0, 0), 1) == "", "room placed rotated")
	check(s2.occupied.size() == 4, "room occupies four cells")
	check(s2.occupied.has(Vector3i(1, 0, -1)), "rotated cell offset is right")
	var s3 := ShipData.new(lib)
	s3.add(&"shaft", Vector3i(0, 0, 0), 0)
	check(s3.add(&"shaft", Vector3i(0, 1, 0), 0) == "", "shaft stacks on shaft")
	check(s3.add(&"corridor", Vector3i(0, 2, 0), 0) != "", "corridor can't connect to shaft top")

	print("stats")
	var s4 := ShipData.new(lib)
	s4.add(&"cockpit", Vector3i(0, 0, 0), 0)
	s4.add(&"corridor", Vector3i(0, 0, 1), 0)
	var st := ShipStats.compute(s4)
	var m0 := lib.get_def(&"cockpit").mass
	var m1 := lib.get_def(&"corridor").mass
	check(is_equal_approx(st.dry, m0 + m1), "dry mass adds up")
	check(st.cost == lib.get_def(&"cockpit").cost + lib.get_def(&"corridor").cost, "cost adds up")
	var rel: Vector3 = st.com - st.centre
	check(is_equal_approx(rel.z, (m1 * 3.0) / (m0 + m1) - 1.5), "centre of mass sits toward the heavier end")
	check(is_equal_approx(rel.x, 0.0) and is_equal_approx(rel.y, 0.0), "centre of mass on the centreline")
	check(not has_warning(st, "No cockpit"), "cockpit satisfies the helm check")
	check(has_warning(ShipStats.compute(s3), "No cockpit"), "no cockpit is flagged")

	var full := ShipStats.compute(ship)  # cockpit, corridor, engineering, engine, frame, radiator
	check(full.thrust_fwd == 80.0, "engine thrust points forward")
	check(full.power_gen == 100.0 and full.power_use == 18.0, "power balance")
	check(full.cooling == 60.0 and full.heat_gen == 148.0, "heat balance")
	check(has_warning(full, "Overheating"), "overheating flagged")
	check(not has_warning(full, "Power short"), "power is fine")

	var s5 := ShipData.new(lib)  # engine mounted well off the centre of mass
	s5.add(&"engineering", Vector3i(0, 0, 0), 0)
	s5.add(&"frame", Vector3i(1, 0, 0), 0)
	s5.add(&"engine", Vector3i(1, 0, 1), 0)
	check(has_warning(ShipStats.compute(s5), "Thrust is"), "off-axis thrust flagged")
	var s6 := ShipData.new(lib)  # engine straight behind: no offset warning
	s6.add(&"engineering", Vector3i(0, 0, 0), 0)
	s6.add(&"engine", Vector3i(0, 0, 1), 0)
	check(not has_warning(ShipStats.compute(s6), "Thrust is"), "on-axis thrust is fine")
	var s7 := ShipData.new(lib)  # engine bolted on sideways, pushing the ship west
	s7.add(&"engineering", Vector3i(0, 0, 0), 0)
	s7.add(&"frame", Vector3i(1, 0, 0), 0)
	check(s7.add(&"engine", Vector3i(2, 0, 0), 1) == "", "engine mounts sideways on the frame")
	check(has_warning(ShipStats.compute(s7), "Some engines"), "misaligned engine flagged")

	print("cargo")
	var s9 := ShipData.new(lib)
	s9.add(&"cockpit", Vector3i(0, 0, 0), 0)
	s9.add(&"corridor", Vector3i(0, 0, 1), 0)
	check(s9.add(&"cargo_hold", Vector3i(0, 0, 2), 0) == "", "hold snaps onto corridor door")
	check(s9.add(&"cargo_hold", Vector3i(0, 0, 4), 0) == "", "second hold chains behind the first")
	s9.remove_at(Vector3i(0, 0, 4))
	check(s9.add(&"cargo_rack", Vector3i(1, 0, 2), 0) == "", "rack bolts onto the hold's bare side")
	check(s9.add(&"cargo_rack", Vector3i(0, 0, 1), 0) != "", "rack can't bolt over a doorway or overlap")
	var cs := ShipStats.compute(s9, 1.0)
	check(cs.cargo_slots == 8 and is_equal_approx(cs.cargo_capacity, 64.0), "cargo capacity adds up")
	var c0 := ShipStats.compute(s9, 0.0)
	var c5 := ShipStats.compute(s9, 0.5)
	check(is_equal_approx(c0.cargo_mass, 0.0) and is_equal_approx(c5.cargo_mass, 32.0), "cargo mass follows load")
	check(is_equal_approx(c5.loaded, c5.wet + 32.0), "loaded mass is wet plus cargo")
	check(is_equal_approx(c0.loaded, c0.wet), "empty hold adds no mass")
	check(cs.com.x > c0.com.x, "full rack pulls the centre of mass toward its side")
	check(not has_warning(cs, "No cargo"), "ship with cargo space has no cargo warning")
	check(has_warning(ShipStats.compute(s4), "No cargo"), "ship without cargo space is flagged")
	var cargo_rows := lib.order.filter(func(id: StringName) -> bool: return lib.get_def(id).group == &"cargo")
	check(cargo_rows.size() == 2, "palette has two cargo modules")
	var json9 := ShipData.new(lib)
	check(json9.from_json(s9.to_json()) and json9.modules.size() == s9.modules.size(), "cargo ship saves and loads")

	print("loading and unloading")
	var cm := CargoManifest.new(s9)  # hold: 4 x 6 t (slots 0-3), rack: 4 x 10 t (slots 4-7)
	check(cm.slots().size() == 8 and is_equal_approx(cm.capacity(), 64.0), "eight containers, 64 t")
	check(is_equal_approx(cm.slots()[0].capacity, 6.0) and is_equal_approx(cm.slots()[4].capacity, 10.0), "container sizes per module")
	check(is_equal_approx(cm.load(&"water", 5.0), 5.0), "partial load goes aboard")
	check(cm.slots_in_use() == 1, "a part-full load opens one container")
	check(is_equal_approx(cm.load(&"water", 3.0), 3.0) and cm.slots_in_use() == 2, "second load tops up then opens another")
	check(is_equal_approx(cm.contents[CargoManifest.slot_key(Vector3i(0, 0, 2), 0)].tonnes, 6.0), "first container topped up to 6 t")
	check(is_equal_approx(cm.load(&"ore", 4.0), 4.0) and cm.slots_in_use() == 3, "different goods never share a container")
	check(is_equal_approx(cm.free_space_for(&"water"), 50.0), "free space counts empty containers plus its own part-full ones")
	check(is_equal_approx(cm.total(), 12.0), "total aboard")
	check(is_equal_approx(cm.total_of(&"water"), 8.0) and is_equal_approx(cm.total_of(&"ore"), 4.0), "totals per commodity")
	var got := cm.load(&"food", 1000.0)
	check(is_equal_approx(got, 46.0), "oversized load takes only what fits")
	check(cm.free_space_for(&"food") < 0.001, "ship is then full of food")
	check(is_equal_approx(cm.total(), 58.0), "other goods keep their part-full containers")
	cm.contents.clear()

	cm.load(&"ore", 10.0)  # location only has 10 t: hold is far from full
	check(is_equal_approx(cm.total(), 10.0) and cm.free_space_for(&"ore") == 54.0, "short supply leaves space free")
	check(is_equal_approx(cm.load(&"ore", 100.0), 54.0), "can top up to the very last tonne")
	check(cm.load(&"ore", 1.0) == 0.0, "full ship loads nothing more")
	check(cm.load(&"unobtainium", 5.0) == 0.0, "unknown goods rejected")
	cm.contents.clear()

	cm.load(&"water", 9.0)  # slots 0 (6 t) and 1 (3 t)
	check(is_equal_approx(cm.unload(&"water", 2.0), 2.0), "unload returns what came off")
	check(is_equal_approx(cm.contents[CargoManifest.slot_key(Vector3i(0, 0, 2), 0)].tonnes, 6.0), "full container left alone")
	check(is_equal_approx(cm.contents[CargoManifest.slot_key(Vector3i(0, 0, 2), 1)].tonnes, 1.0), "emptiest container drained first")
	check(is_equal_approx(cm.unload(&"water", 100.0), 7.0), "unloading more than aboard returns what was there")
	check(cm.slots_in_use() == 0, "empty containers close")
	check(cm.unload(&"water", 5.0) == 0.0, "nothing to unload")

	cm.load(&"machinery", 30.0)
	check(is_equal_approx(cm.value(), 30.0 * 600.0), "cargo value")
	var gone := cm.unload_all()
	check(is_equal_approx(gone[&"machinery"], 30.0) and cm.total() == 0.0, "unload all")

	cm.load(&"ore", 8.0)
	check(cm.blocks_removal(Vector3i(0, 0, 2)) != "", "can't remove a hold with cargo in it")
	check(cm.blocks_removal(Vector3i(0, 0, 1)) == "", "empty corridor can go")
	var cst := ShipStats.compute(s9, 1.0, cm)
	check(is_equal_approx(cst.cargo_mass, 8.0) and is_equal_approx(cst.loaded, cst.wet + 8.0), "stats use the real manifest")
	check(cst.cargo_used_slots == 2 and is_equal_approx(cst.cargo_value, 8.0 * 90.0), "stats report containers used and value")
	var empty_cm := CargoManifest.new(s9)
	check(ShipStats.compute(s9, 1.0, empty_cm).com.x < cs.com.x, "empty ship balances differently to a full one")
	var round_trip := CargoManifest.new(s9)
	round_trip.from_dict(JSON.parse_string(JSON.stringify(cm.to_dict())))
	check(is_equal_approx(round_trip.total_of(&"ore"), 8.0), "manifest saves and loads")
	round_trip.from_dict({"9,9,9:0": {"commodity": "ore", "tonnes": 3}, "0,0,2:0": {"commodity": "ore", "tonnes": 99}, "0,0,2:1": {"commodity": "junk", "tonnes": 1}})
	check(is_equal_approx(round_trip.total(), 6.0), "bad saved cargo dropped or clamped")
	var gone_ship := ShipData.new(lib)
	gone_ship.add(&"cockpit", Vector3i(0, 0, 0), 0)
	var stale := CargoManifest.new(gone_ship)
	stale.contents["0,0,2:0"] = {"commodity": &"ore", "tonnes": 5.0}
	stale.prune()
	check(stale.contents.is_empty(), "cargo of a missing module is pruned")

	print("sealed hull and airlock")
	var sealed := ShipData.new(lib)
	sealed.add(&"cockpit", Vector3i(0, 0, 0), 0)
	check(sealed.open_doors().size() == 1, "cockpit's rear door opens onto space")
	sealed.add(&"corridor", Vector3i(0, 0, 1), 0)
	check(sealed.open_doors().size() == 1, "still one open door at the corridor's far end")
	check(sealed.add(&"airlock", Vector3i(0, 0, 2), 1) != "", "airlock must face its door at the ship")
	check(sealed.add(&"airlock", Vector3i(0, 0, 2), 0) != "", "airlock door faces west, not the corridor")
	check(sealed.add(&"airlock", Vector3i(0, 0, 2), 3) == "", "airlock turned so its door faces the corridor")
	check(sealed.open_doors().is_empty(), "airlock caps the hull")
	var sst := ShipStats.compute(sealed)
	check(sst.airlocks == 1 and sst.open_doors == 0, "stats count airlocks and open doors")
	check(not has_warning(sst, "Hull open") and not has_warning(sst, "No airlock"), "no hull warnings once sealed")
	check(has_warning(ShipStats.compute(s4), "Hull open") and has_warning(ShipStats.compute(s4), "No airlock"), "open hull and missing airlock flagged")
	var blocked := ShipData.new(lib)
	blocked.add(&"engineering", Vector3i(0, 0, 0), 0)
	blocked.add(&"engine", Vector3i(0, 0, 1), 0)
	check(blocked.open_doors().size() == 1, "door facing an engine is still open to space")

	print("starter ship")
	var starter := ShipData.new(lib)
	check(ShipPresets.build(starter) == "", "starter ship builds through the normal rules")
	var stst := ShipStats.compute(starter, 1.0)
	check(stst.open_doors == 0 and stst.airlocks == 1 and stst.has_helm, "starter is sealed, has an airlock and cockpit")
	check(stst.power_use <= stst.power_gen and stst.heat_gen <= stst.cooling, "starter power and cooling balance")
	check(stst.warnings.size() == 0, "starter has no warnings: %s" % str(stst.warnings))
	check(stst.cost < 150000, "starter is affordable")
	check(stst.twr_loaded > 0.14, "starter can lift a full hold")

	print("contracts")
	var smf := CargoManifest.new(starter)
	var k0 := Contracts.get_contract(0)
	check(not Contracts.ready(Contracts.check(stst, smf, k0)), "can't run without cargo aboard")
	smf.load(k0.commodity, k0.offer)
	check(Contracts.ready(Contracts.check(ShipStats.compute(starter, 1.0, smf), smf, k0)), "starter can run the water contract")
	check(Contracts.pay(smf, k0) == 9000, "pays rate times tonnes")
	var k1 := Contracts.get_contract(1)
	var smf2 := CargoManifest.new(starter)
	smf2.load(k1.commodity, k1.offer)  # 60 t offered, 24 t of room
	check(is_equal_approx(smf2.total(), 24.0), "short on space: takes what fits")
	check(Contracts.pay(smf2, k1) == roundi(24.0 * 380.0), "pays only for what was carried")
	check(Contracts.best_pay(smf2, k1) == Contracts.pay(smf2, k1), "full ship earns the best pay")
	var k4 := Contracts.get_contract(4)
	var smf3 := CargoManifest.new(starter)
	smf3.load(k4.commodity, k4.offer)
	check(not Contracts.ready(Contracts.check(ShipStats.compute(starter, 1.0, smf3), smf3, k4)), "rush job needs a faster ship")
	var broken := ShipData.new(lib)
	ShipPresets.build(broken)
	broken.remove_at(Vector3i(1, 0, 1))  # take off the airlock
	var bmf := CargoManifest.new(broken)
	bmf.load(k0.commodity, 5.0)
	var rows := Contracts.check(ShipStats.compute(broken, 1.0, bmf), bmf, k0)
	check(not Contracts.ready(rows), "missing airlock blocks the run")

	print("undo and redo")
	var hist := ShipHistory.new()
	check(not hist.can_undo() and not hist.can_redo(), "history starts empty")
	hist.record({"n": 1})
	check(hist.can_undo(), "recording enables undo")
	var back := hist.undo({"n": 2})
	check(back.n == 1 and hist.can_redo(), "undo returns the earlier state")
	var fwd := hist.redo({"n": 1})
	check(fwd.n == 2, "redo returns the later state")
	hist.undo({"n": 2})
	hist.record({"n": 9})
	check(not hist.can_redo(), "a new edit clears redo")

	print("save and load")
	var json := ship.to_json()
	var s8 := ShipData.new(lib)
	check(s8.from_json(json), "json loads (mounts count as connections)")
	check(s8.modules.size() == ship.modules.size(), "same module count")
	check(s8.occupied.keys().size() == ship.occupied.keys().size(), "same occupied cells")
	check(not s8.from_json("not json"), "garbage rejected")
	check(not s8.from_json('{"modules":[{"id":"nope","cell":[0,0,0]}]}'), "unknown module rejected")
	check(s8.modules.size() == ship.modules.size(), "failed load leaves ship untouched")

	print("")
	print("FAILED: %d" % failures if failures > 0 else "all passed")
	quit(1 if failures > 0 else 0)
